2020-03-04 21:28:53,644 ERROR: Exception on / [GET] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Rating' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 15, in index
    tracks = Track.query.all()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 517, in __get__
    mapper = orm.class_mapper(type)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\base.py", line 441, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\base.py", line 420, in _inspect_mapped_class
    mapper._configure_all()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1337, in _configure_all
    configure_mappers()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3248, in configure_mappers
    mapper._post_configure_properties()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 196, in init
    self.do_init()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1878, in do_init
    self._process_dependent_arguments()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1940, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1845, in entity
    argument = self.argument()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Rating' failed to locate a name ("name 'Rating' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.User'> class after both dependent classes have been defined.
2020-03-04 21:29:57,358 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:60]
2020-03-04 21:30:04,070 ERROR: Exception on / [GET] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Rating' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 15, in index
    tracks = Track.query.all()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 517, in __get__
    mapper = orm.class_mapper(type)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\base.py", line 441, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\base.py", line 420, in _inspect_mapped_class
    mapper._configure_all()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1337, in _configure_all
    configure_mappers()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3248, in configure_mappers
    mapper._post_configure_properties()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 196, in init
    self.do_init()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1878, in do_init
    self._process_dependent_arguments()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1940, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1845, in entity
    argument = self.argument()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\sqlalchemy\ext\declarative\clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->user, expression 'Rating' failed to locate a name ("name 'Rating' is not defined"). If this is a class name, consider adding this relationship() to the <class 'app.models.User'> class after both dependent classes have been defined.
2020-03-04 21:32:04,316 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:60]
