2020-03-10 13:34:38,460 ERROR: Exception on /user/20 [POST] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 38, in user
    recommendations = user.get_recommendations(context_form.to_context())
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\models.py", line 61, in get_recommendations
    weight += B[i, context[key]]
IndexError: index 42 is out of bounds for axis 1 with size 24
2020-03-10 13:46:42,740 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-10 13:48:08,107 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-10 13:49:52,288 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-10 13:50:13,844 ERROR: Exception on /user/20 [GET] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 38, in user
    recommendations = user.get_recommendations(context_form.to_context())
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\models.py", line 63, in get_recommendations
    print(context + " -> " + weight)
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
2020-03-10 13:50:46,183 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-10 13:51:34,026 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
